version: "1.0"
devices:
  - name: Router-1
    ip: 10.0.0.1
    vendor: Cisco

  - name: Router-2
    ip: 10.0.0.2
    vendor: Huawei

  - name: Router-3
    ip: 10.0.0.3
    vendor: Juniper

  - name: Router-4
    ip: 10.0.0.4
    vendor: MikroTik


